# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from depart import *
from PyQt5 import QtCore, QtGui, QtWidgets

temp = 0

class MainWindow(QtWidgets.QMainWindow, Ui_mainWindow):
    def __init__(self):  # 初始化UI代码
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.p0.clicked.connect(self.f0)
        self.p1.clicked.connect(self.f1)
        self.p2.clicked.connect(self.f2)
        self.p3.clicked.connect(self.f3)
        self.p4.clicked.connect(self.f4)
        self.p5.clicked.connect(self.f5)
        self.p6.clicked.connect(self.f6)
        self.p7.clicked.connect(self.f7)
        self.p8.clicked.connect(self.f8)
        self.p9.clicked.connect(self.f9)
        self.p10.clicked.connect(self.f10)
        self.p11.clicked.connect(self.f11)
        self.p12.clicked.connect(self.f12)
        self.p13.clicked.connect(self.f13)
        
        self.p14.clicked.connect(self.RUN)
        
        self.pc.clicked.connect(self.clean)
        
    def clean(self):
        self.label.setText("")
        
    def f0(self):
        self.label.setText(self.label.text()+"0")
    def f1(self):
        self.label.setText(self.label.text()+"1")
    def f2(self):
        self.label.setText(self.label.text()+"2")
    def f3(self):
        self.label.setText(self.label.text()+"3")        
    def f4(self):
        self.label.setText(self.label.text()+"4")        
    def f5(self):
        self.label.setText(self.label.text()+"5")        
    def f6(self):
        self.label.setText(self.label.text()+"6")
    def f7(self):
        self.label.setText(self.label.text()+"7")
    def f8(self):
        self.label.setText(self.label.text()+"8")
    def f9(self):
        self.label.setText(self.label.text()+"9")
    def f10(self):
        self.label.setText(self.label.text()+"+")
    def f11(self):
        self.label.setText(self.label.text()+"-")
    def f12(self):
        self.label.setText(self.label.text()+"x")
    def f13(self):
        self.label.setText(self.label.text()+"÷")
        
    def RUN(self):
        self.label.setText(self.label.text()+"=")
        a=list(self.label.text())
        # a=["5","+","8","x","9","÷","6","="]
        res=0
        data=[]
        op=[]
        flag=0
        res=0.0
        for i in range(len(a)):
            if a[i] == '0' or a[i] == '1' or a[i] == '2' or a[i] == '3' or a[i] == '4' or a[i] == '5' or a[i] == '6' or a[i] == '7' or a[i] == '8' or a[i] == '9':
                flag+=1
            else:
                t=""
                for j in range(flag):
                    t=a[i-j-1]+t
                    
                data.append(float(t)) 
                if a[i]!='=':
                    op.append(a[i])
                flag=0
        
         
        if 'x' in op or '÷' in op: 
            ox=[]
            oy=[]
            for i in range(len(op)):
                if op[i] == "x" :
                    ox.append(i)
                    
                if op[i] == '÷':
                    oy.append(i)
              
              
            OO=ox+oy
            OO.sort(reverse=True)  
                                          
            for i in OO:
                if op[i]=="x":
                    data[i]=data[i]*data[i+1]
                    data.pop(i+1)
                if op[i]=='÷':
                    data[i]=data[i]/data[i+1]
                    data.pop(i+1)
            
           
            for i in OO:
                    op.pop(i)
            
            res = data[0]
            if len(data)==1:
                pass
            else:
                for i in range(len(op)):
                    if op[i] == '+':
                        res=res+data[i+1]
                    else :
                        res=res-data[i+1]
            
        else:
            
            res = data[0]
            for i in range(len(op)):
                if op[i] == '+':
                    res=res+data[i+1]
                else :
                    res=res-data[i+1]
      
        self.label.setText(self.label.text()+str(res))    
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    sys.exit(app.exec_())
    
